### PR TITLE
Aws v3

### PR DESCRIPTION
**Pull request by ktonon**

### CODE REVIEW

**Comment by MichaelKovalchuk** [comment]
should we archive/graveyard this in the future?

**Comment by ktonon** [comment]
> should we archive/graveyard this in the future?

Yes, once we deploy https://github.com/Brightspace/step-functions-lambda-worker-wrapper/pull/53 I'll look into graveyarding this

**Comment by ktonon** [comment]
Founds these references to `step-function-worker`
https://search.d2l.dev/search?project=Brightspace&project=Brightspace-Configs&project=BrightspaceHypermediaComponents&project=BrightspaceUI&project=BrightspaceUILabs&project=lms&full=%22step-function-worker%22&defs=&refs=&path=&hist=&type=&xrd=&nn=6

- [Brightspace/d2l-content-service-worker-unzip](https://github.com/Brightspace/d2l-content-service-worker-unzip/blob/master/package.json#L49): will be fixed by [MED-786](https://desire2learn.atlassian.net/browse/MED-786)
- The ref to `Brightspace/step-functions-lambda-worker-wrapper` is stale, since I just merged the PR (already fixed)
- [Brightspace/d2l-scorm-engine-tools](https://github.com/Brightspace/d2l-scorm-engine-tools/blob/master/package-lock.json#L1684): I don't have this on the roadmap. Could be it was overlooked. I'll check it out today...
- `Brightspace/d2l-content-service`: will be fixed by [MED-778](https://desire2learn.atlassian.net/browse/MED-778)

**Comment by ktonon** [comment]
re: scorm engine tools:

```shell
> npm ls aws-sdk
@d2l/scorm-engine-tools@2.0.2 /Users/ktonon/repo/cs/scorm-engine-tools
├─┬ @d2l/cabinet-deployment@8.3.9
│ └── aws-sdk@2.1372.0
├─┬ @d2l/cs-tools@9.0.1
│ ├─┬ @d2l/kms-crypt@1.1.1
│ │ └── aws-sdk@2.1372.0 deduped
│ └── aws-sdk@2.1372.0 deduped
└─┬ @d2l/step-functions-lambda-worker-wrapper@1.2.6
  └─┬ step-function-worker@0.0.3 (git+ssh://git@github.com/Brightspace/step-function-worker.git#af9a581f4b458d405ff5784924d65b2dfb701406)
    └── aws-sdk@2.1372.0 deduped
```

Created [MED-849](https://desire2learn.atlassian.net/browse/MED-849) to track it

**Pull request closed without merging**
